In [49]:
import pandas as pd
import numpy as np
df = pd.read_csv("../data/healthcare_dataset.csv")
print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 55500
Columns: 15

In [ ]:
# Data Ingestion, Cleaning & Preprocessing with Pandas

In [ ]:
# 1. Initial inspection

In [50]:
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [52]:
df.describe()

                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224652    202.000000
50%       52.000000    25538.069376    302.000000
75%       68.000000    37820.508436    401.000000
max       89.000000    52764.276736    500.000000

In [ ]:
# 2. Check missing values

In [53]:
print("Missing values in each column:")
print(df.isnull().sum())
print("\nTotal missing values:", df.isnull().sum().sum())

Missing values in each column:
Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

Total missing values: 0

In [ ]:
# 3. Check and remove duplicates

In [54]:
print("Duplicate rows before cleaning:", df.duplicated().sum())

Duplicate rows before cleaning: 534

In [55]:
df = df.drop_duplicates()
print("Duplicate rows after cleaning:", df.duplicated().sum())
print("New shape:", df.shape)

Duplicate rows after cleaning: 0
New shape: (54966, 15)

In [ ]:
# 4. Correct date data types

In [56]:
print(df.dtypes)

Name                   object
Age                     int64
Gender                 object
Blood Type             object
Medical Condition      object
Date of Admission      object
Doctor                 object
Hospital               object
Insurance Provider     object
Billing Amount        float64
Room Number             int64
Admission Type         object
Discharge Date         object
Medication             object
Test Results           object
dtype: object

In [57]:
df["Date of Admission"] = pd.to_datetime(
    df["Date of Admission"],
    errors="coerce"
)

df["Discharge Date"] = pd.to_datetime(
    df["Discharge Date"],
    errors="coerce"
)
print(df[["Date of Admission", "Discharge Date"]].dtypes)

Date of Admission    datetime64[ns]
Discharge Date       datetime64[ns]
dtype: object

In [ ]:
# 5. Handle outliers

In [58]:
Q1 = df["Billing Amount"].quantile(0.25)
Q3 = df["Billing Amount"].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[
    (df["Billing Amount"] < lower_bound) |
    (df["Billing Amount"] > upper_bound)
]
print("Number of outliers:", len(outliers))

Number of outliers: 0

In [59]:
df["Billing Amount"] = df["Billing Amount"].clip(
    lower=lower_bound,
    upper=upper_bound
)

print("Outliers handled successfully.")

Outliers handled successfully.

In [ ]:
# 6. Feature engineering

In [60]:
df["Admission Year"] = df["Date of Admission"].dt.year
df["Admission Month"] = df["Date of Admission"].dt.month

df["Length of Stay"] = (
    df["Discharge Date"] - df["Date of Admission"]
).dt.days

df[
    [
        "Date of Admission",
        "Discharge Date",
        "Admission Year",
        "Admission Month",
        "Length of Stay"
    ]
].head()

,Date of Admission,Discharge Date,Admission Year,Admission Month,Length of Stay
0,2024-01-31,2024-02-02,2024,1,2
1,2019-08-20,2019-08-26,2019,8,6
2,2022-09-22,2022-10-07,2022,9,15
3,2020-11-18,2020-12-18,2020,11,30
4,2022-09-19,2022-10-09,2022,9,20

In [ ]:
## 7. Profit Margin

Profit margin calculation is not applicable because the provided
healthcare dataset does not contain separate Revenue and Cost columns.
Therefore, a valid profit margin cannot be calculated without
introducing fabricated data.

In [ ]:
# 8. Standardize text

In [61]:
text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    df[col] = df[col].str.strip()

df["Name"] = df["Name"].str.title()
df["Doctor"] = df["Doctor"].str.title()

print("Text standardization completed.")

Text standardization completed.

In [ ]:
# 9 .Final check

In [62]:
print("Final shape:", df.shape)
print("Total missing values:", df.isnull().sum().sum())
print("Total duplicate rows:", df.duplicated().sum())

Final shape: (54966, 18)
Total missing values: 0
Total duplicate rows: 0

In [ ]:
# 10. Exporting file

In [63]:
df.to_csv("clean_dataset.csv", index=False)

print("clean_dataset.csv created successfully!")

clean_dataset.csv created successfully!

In [48]:
clean_df = pd.read_csv("clean_dataset.csv")

print("Rows:", clean_df.shape[0])
print("Columns:", clean_df.shape[1])

clean_df.head()

Rows: 54966
Columns: 18

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Admission Year,Admission Month,Length of Stay
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,2024,1,2
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,2019,8,6
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,2022,9,15
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,2020,11,30
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,2022,9,20

In [ ]:
## Before vs After Cleaning
The raw healthcare dataset initially contained 55,500 records and 15 columns. Duplicate records, data type inconsistencies, and outliers were examined during preprocessing.
After cleaning, duplicate records were removed, date columns were converted to datetime format, outliers were handled, and new features were created.
The final standardized dataset contains 54,966 records and 18 columns.

In [65]:
# Before vs After Cleaning Comparison

print("BEFORE CLEANING")
print("Rows:", 55500)
print("Columns:", 15)
print("Duplicate rows:", 534)

print("\nAFTER CLEANING")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Duplicate rows:", df.duplicated().sum())
print("Missing values:", df.isnull().sum().sum())

BEFORE CLEANING
Rows: 55500
Columns: 15
Duplicate rows: 534

AFTER CLEANING
Rows: 54966
Columns: 18
Duplicate rows: 0
Missing values: 0